apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-cluster
spec:
  destination:
    name: ''
    namespace: 'default'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'capi-cluster/aws-eks'
    repoURL: 'git@github.com:perejal/eks-ec2-clusterapi-gitops.git'
    targetRevision: HEAD
    #helm:
     # valueFiles:
       # - values-c1.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
